CREATE TABLE IF NOT EXISTS localMiniBlocks (
        miniBlock_index integer(100) NOT NULL,
        id varchar(255) NOT NULL,
        round integer,
        parent_hash varchar(255),
        hash varchar(255) NOT NULL,
        owner_pubkey varchar(255),
        signed_node_hash varchar(255),
        merkle_root varchar(255),
        ticket_number integer(100),
        transactions longtext,
        arrive_time integer,
        confirmed integer,
        subuser integer,
        numSuc integer,
        round_stable integer default 0,
        PRIMARY KEY (id,miniBlock_index))
